# Generated by Django 4.2.5 on 2023-10-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asiakas',
            fields=[
                ('asiakas_id', models.AutoField(db_column='asiakas_ID', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('nimi', models.CharField(max_length=60)),
                ('puhnumero', models.CharField(max_length=20)),
                ('sahkoposti', models.CharField(max_length=60)),
                ('osoite', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'asiakas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Juomat',
            fields=[
                ('juoma_id', models.AutoField(db_column='juoma_ID', primary_key=True, serialize=False)),
                ('nimi', models.CharField(max_length=80)),
                ('tilavuus', models.FloatField()),
                ('hinta', models.IntegerField()),
                ('kuva', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'juomat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('admin_id', models.AutoField(db_column='admin_ID', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=25)),
                ('email', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'login',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pizzat',
            fields=[
                ('pizza_id', models.AutoField(db_column='pizza_ID', primary_key=True, serialize=False)),
                ('nimi', models.CharField(max_length=80)),
                ('koko', models.CharField(max_length=50)),
                ('taytteet', models.CharField(max_length=100)),
                ('hinta', models.IntegerField()),
                ('kuva', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pizzat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tilaus',
            fields=[
                ('tilaus_id', models.IntegerField(db_column='tilaus_ID', primary_key=True, serialize=False)),
                ('asiakas_id', models.IntegerField(db_column='asiakas_ID')),
                ('hinta', models.DecimalField(decimal_places=0, max_digits=65)),
                ('pvm', models.DateField()),
            ],
            options={
                'db_table': 'tilaus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tilausrivi',
            fields=[
                ('tilriv_id', models.IntegerField(db_column='tilRiv_ID', primary_key=True, serialize=False)),
                ('kpl', models.IntegerField()),
            ],
            options={
                'db_table': 'tilausrivi',
                'managed': False,
            },
        ),
    ]
